# Navigation Links
# To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
# desired widget in your `content/home/` folder.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10
  
[[main]]
  name = "Skills"
  url = "#skills"
  weight = 15

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 20

[[main]]
  name = "Awards"
  url = "#accomplishments"
  weight = 30

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 40

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 50

[[main]]
  name = "Blog"
  url = "https://blog.csdn.net/weixin_43823054"
  weight = 60

[[main]]
  name = "CV"
  url = "cv/"
  weight = 70
